apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    test-key: "test-value"
    test-key-1: "test-value-1"
    test-key-2: "test-value-2"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
